version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anb-frontend-prod
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=_
      - NGINX_PORT=80
