FROM nginx:alpine
COPY ./browser /usr/share/nginx/html
COPY default.conf.template /etc/nginx/templates/default.conf.template
RUN if [ -f /usr/share/nginx/html/index.csr.html ]; then mv /usr/share/nginx/html/index.csr.html /usr/share/nginx/html/index.html; fi
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]