version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anb-api-prod
    command: /app/api_server
    ports:
      - "9090:9090"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Database (RDS requiere SSL)
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=require
      
      # JWT
      - JWT_SECRET=${JWT_SECRET}
      
      # Redis
      - REDIS_ADDR=${REDIS_ADDR}
      
      # Server
      - SERVER_PORT=${SERVER_PORT}
      
      # S3 Storage
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
      
      # AWS Credentials
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
